//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheProject.BoundryPolygons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int Id { get; set; }
        public string BuildingName { get; set; }
        public string BuildingNumber { get; set; }
        public string BuildingType { get; set; }
        public string BuildingStandard { get; set; }
        public string Status { get; set; }
        public int NumberOfFloors { get; set; }
        public double FootPrintArea { get; set; }
        public double ImprovedArea { get; set; }
        public bool Heritage { get; set; }
        public string OccupationYear { get; set; }
        public string DisabledAccess { get; set; }
        public string DisabledComment { get; set; }
        public string ConstructionDescription { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> GPSCoordinates_Id { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual GPSCoordinate GPSCoordinate { get; set; }
    }
}
